export const DATA_REQUEST = 'DATA_REQUEST';
export const DATA_SUCCESS = 'DATA_SUCCESS';
export const DATA_FAILURE = 'DATA_FAILURE';
export const FIRST_LOAD_REQUEST = 'FIRST_LOAD_REQUEST';
export const FIRST_LOAD_SUCCESS = 'FIRST_LOAD_SUCCESS';
export const RESET_ERROR = 'RESET_ERROR';
export const CHANGE_FILTER = 'CHANGE_FILTER';
